# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ec6e7a76150b4bb15bb27e47b7afda1158f19b82e3d4b08b75a49871fade26bdc9194748082abdcde413d46746a59d0fee8fa08ddf8928ea657e5a9b9999cd

test:
  secret_key_base: 47ccb2149cc20dc495f4984c14f63b84a9af8d548cf36a521e7f6754cab5ca7a3ebb635689e41b5f869ddd04a2f877727347ce32ba5a86bf82fff8eeb943ef98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
